name: "Publish a bot container in Docker"

on:
  workflow_dispatch:
    inputs:
      container:
        description: "The bot container to publish e.g. notarizer, reporter"
        required: true
        type: choice
        options:
          - notarizer
          - reporter
      version:
        description: "The version tag to publish (as settled in package.json)"
        required: true

jobs:
  build:
    env:
      REGISTRY: docker.io
      IMAGE_NAME: witnet/price-feeds-${{ inputs.container }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        usses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ inputs.container }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:$${{ github.ref_name }}
